### ISSUE TITLE
CiviMail open tracking is broken by extension

### ISSUE THREAD

**Issue by agileware-fj** [skyslasher/de.ergomation.wp-civi-mosaico#3]
When sending an email with this plugin enabled, the tracking pixel image is replaced with a relative URL e.g. `<img src="/civicrm/mailing/open" ...>` which obviously will not work.
Additionally the `?qid=...` parameter is removed, so even if the URL was absolute, it would not work for tracking opens.

The system where this issue was discovered has clean URLs enabled for CiviCRM.

There is a related warning displayed during the send process:
> PHP Warning:  mime_content_type({DOCROOT}/wp-content/uploads/civicrm/mailing/open/): failed to open stream: No such file or directory in {DOCROOT}/wp-content/uploads/civicrm/ext/de.ergomation.wp-civi-mosaico/CRM/WpCiviMosaico/EmbedImagesSender.php on line 287

[Code reference for warning](https://github.com/skyslasher/de.ergomation.wp-civi-mosaico/blob/8214b1e09436f23b8ab930666a5a20424825b964/CRM/WpCiviMosaico/EmbedImagesSender.php#L287)

Ideally this should not process the automatically inserted CiviMail URLs at all.

**Comment by skyslasher** [comment]
What Version of CiviCRM are you using? The plugin is scanning for the tracking pixel and leaves it untouched, but it seems that the tracking URL changed from `.../open.php` to `.../open/` so it is not recognized.

**Comment by agileware-fj** [comment]
This is using CiviCRM 5.33.2

**Comment by skyslasher** [comment]
I uploaded a fix today that should eleminate this issue. Can you please check?

**Comment by agileware-fj** [comment]
@skyslasher the fix works with clean URLs, thanks!

I did some additional testing with clean URL disabled and it wasn't working there. Was fairly simple to work around that, I'll submit a PR shortly.

**Comment by skyslasher** [comment]
Merged, please check the merged branch. If everything works we can close the issue

**Comment by agileware-fj** [comment]
Is all working, thanks.

Closing the issue.
